version: "3.1"

services:
  postgres:
    image: postgres
    volumes:
      - ./pgdb/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "detal"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "12345"

  redis:
    container_name: redis
    image: redis
    restart: "on-failure"
    ports:
      - 6369:6369
